name: Repo-Call Calc something

on:
  repository_dispatch:
    types: [calc_test]

jobs:
  call_calc:
    uses: metaodi/fire-forget-calc/.github/workflows/calc.yml@main
    with:
      input_str: ${{ github.event.client_payload.input }}
